[package]
name = "orbital-terminal"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Terminal process for Orbital OS"

[lib]
crate-type = ["cdylib"]

[features]
default = []

[dependencies]
orbital-process.workspace = true
